config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'dashboard', to: 'users#dashboard'

  resources :posts

  get 'u/:username', to: 'users#show', as: 'user'
  post 'u/:username/follow', to: 'users#follow', as: 'follow'
  get 'users/index', to: 'users#index', as: 'users'
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :username, uniqueness: true, null: false, length: { minimum: 2 }

  has_many :follower_records, class_name: 'Follow', foreign_key: 'following_id'
  has_many :followers, through: :follower_records

  has_many :following_records, class_name: 'Follow', foreign_key: 'follower_id'
  has_many :followings, through: :following_records

  has_one_attached :avatar

  has_many :user_posts
  has_many :posts, through: :user_posts
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # Get the input form
  def new
    super
  end

  # POST /resource
  # Post the 'new' input form to the model
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
    if params[:user][:avatar].present?
      @user.avatar.attach(params[:user][:avatar])
      @user.save
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :description, :avatar_url])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :description, :avatar_url])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def dashboard
    @user = current_user
    @followers = @user.followers
    @followings = @user.followings
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @followers = @user.followers
    @followings = @user.followings
    @post = Post.new
  end

  def follow
    @user.followers << current_user
    redirect_to user_path(username: @user.username)
  end

  private
    def set_user
      @user = User.find_by(username: params[:username])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_display_users.html.erb
<% users.each do |user| %>
  <%= link_to user.username, user_path(username: user.username) %>
<% end %>

app/views/users/dashboard.html.erb
<%= link_to 'Account Settings', edit_user_registration_path %>
<h1>Dashboard</h1>
<h2>Followers</h2>
<%= render 'display_users', users: @followers %>
<h2>Followings</h2>
<%= render 'display_users', users: @followings %>
<%= link_to 'My Profile', user_path(username: current_user.username) %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Description</th>
      <th>Avatar url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.description %></td>
        <td><%= user.avatar_url %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Avatar url:</strong>
  <%= image_tag @user.avatar_url %>
</p>

<p>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar.variant(resize: "200x200") %>
  <% else %>
    <p>User does not have an avatar</p>
  <% end %>
</p>

<h2>Followers</h2>
<%= render 'display_users', users: @followers %>
<h2>Followings</h2>
<%= render 'display_users', users: @followings %>

<%= link_to 'Follow', follow_path(username: @user.username), method: :post %>

<% if @user == current_user %>
  <%= render 'posts/form',  post: @post %>
<% end %>

<h2>Posts</h2>
<ul>
  <% @user.posts.each do |post| %>
    <li><%= post.data %></li>
  <% end %>
</ul>